package frc.robot.subsystems

import com.ctre.phoenix6.Utils
import com.ctre.phoenix6.swerve.SwerveModule
import com.ctre.phoenix6.swerve.SwerveRequest
import edu.wpi.first.math.MathUtil
import edu.wpi.first.math.Matrix
import edu.wpi.first.math.VecBuilder
import edu.wpi.first.math.controller.PIDController
import edu.wpi.first.math.filter.SlewRateLimiter
import edu.wpi.first.math.geometry.Pose2d
import edu.wpi.first.math.geometry.Rotation2d
import edu.wpi.first.math.numbers.N1
import edu.wpi.first.math.numbers.N3
import edu.wpi.first.units.Units.RotationsPerSecond
import edu.wpi.first.units.measure.Distance
import edu.wpi.first.wpilibj.DriverStation
import edu.wpi.first.wpilibj.DriverStation.Alliance.Red
import edu.wpi.first.wpilibj.Notifier
import edu.wpi.first.wpilibj.RobotController
import frc.robot.FieldConstants.BLUE_AUTO_LINE_X
import frc.robot.FieldConstants.FEED_LEFT_POSE
import frc.robot.FieldConstants.FEED_RIGHT_POSE
import frc.robot.FieldConstants.HUB_POSE
import frc.robot.FieldConstants.LEFT_CLIMB_POSE
import frc.robot.FieldConstants.LEFT_PRE_CLIMB_POSE
import frc.robot.FieldConstants.RED_AUTO_LINE_X
import frc.robot.FieldConstants.RIGHT_CLIMB_POSE
import frc.robot.FieldConstants.RIGHT_PRE_CLIMB_POSE
import frc.robot.OI
import frc.robot.generated.TunerConstants
import frc.robot.generated.TunerConstants.kSpeedAt12Volts
import frc.robot.lib.LimelightHelpers
import frc.robot.lib.degrees
import frc.robot.lib.inches
import frc.robot.lib.meters
import frc.robot.lib.metersPerSecond
import java.util.*
import java.util.function.Consumer
import kotlin.math.abs
import kotlin.math.hypot
import kotlin.math.roundToInt
import kotlin.math.sign
import org.littletonrobotics.junction.Logger

/**
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
object SwerveDrivetrain :
    TunerConstants.TunerSwerveDrivetrain(
        TunerConstants.DrivetrainConstants,
        TunerConstants.FrontLeft,
        TunerConstants.FrontRight,
        TunerConstants.BackLeft,
        TunerConstants.BackRight,
    ) {

    enum class SwerveState {
        FieldCentric,
        OrientToHub,
        CrossBump,
        XBrake,
        AlignToTower,
        CardinalSnap,
    }

    var currentState = SwerveState.FieldCentric
        set(newState) {
            if (newState == SwerveState.CrossBump) {
                // round to nearest 45-degree offset: 45, 135, -135, -45
                val operatorRelativeHeading =
                    state.Pose.rotation.minus(operatorForwardDirection).degrees
                val snapDegrees =
                    ((operatorRelativeHeading - 45.0) / 90.0).roundToInt() * 90.0 + 45.0
                crossBumpSnapAngle = Rotation2d(snapDegrees.degrees)
                //                OI.isDeployed = false

                // Old version below that enforces back-first for old intake

                // val xMeters = state.Pose.x
                // val isBlue =
                //     DriverStation.getAlliance().orElse(DriverStation.Alliance.Red) ==
                //         DriverStation.Alliance.Blue
                // // true = back toward driver side (+- 45°), false = front toward driver side (+-
                // // 135°)
                // val backTowardsDriver =
                //     when {
                //         xMeters < FieldConstants.BLUE_AUTO_LINE_X -> !isBlue
                //         xMeters < FieldConstants.MIDPOINT.x -> isBlue
                //         xMeters < FieldConstants.RED_AUTO_LINE_X -> !isBlue
                //         else -> isBlue
                //     }
                // val snapDegrees =
                //     if (backTowardsDriver) {
                //         if (operatorRelativeHeading >= 0) 45.0 else -45.0
                //     } else {
                //         if (operatorRelativeHeading >= 0) 135.0 else -135.0
                //     }
                // crossBumpSnapAngle = Rotation2d(snapDegrees.degrees)
            }

            if (newState == SwerveState.CardinalSnap) {
                cardinalSnapDirection =
                    when {
                        OI.snapNorth() -> Rotation2d.kZero
                        OI.snapEast() -> Rotation2d.kCW_90deg
                        OI.snapSouth() -> Rotation2d.k180deg
                        OI.snapWest() -> Rotation2d.kCCW_90deg
                        else -> cardinalSnapDirection
                    }
            }

            if (newState == SwerveState.AlignToTower) climbPreAligned = false

            field = newState
        }

    var crossBumpSnapAngle = Rotation2d.kZero
    var cardinalSnapDirection = Rotation2d.kZero
    private val crossBumpPIDController = PIDController(5.0, 0.0, 0.5)
    var climbPreAligned = false

    private val fieldCentricRequest =
        SwerveRequest.FieldCentric()
            .withDriveRequestType(SwerveModule.DriveRequestType.OpenLoopVoltage)
            .withSteerRequestType(SwerveModule.SteerRequestType.Position)

    private val autoIntakeDriveRequest =
        SwerveRequest.FieldCentricFacingAngle()
            .withHeadingPID(10.0, 0.0, 0.15)
            .withForwardPerspective(SwerveRequest.ForwardPerspectiveValue.BlueAlliance)

    private val crossBumpRequest =
        SwerveRequest.FieldCentricFacingAngle().withHeadingPID(10.0, 0.0, 0.15)

    private val orientHubRequest =
        SwerveRequest.FieldCentricFacingAngle()
            .withHeadingPID(10.0, 0.0, 0.15)
            .withCenterOfRotation(Shooter.Constants.SHOOTER_OFFSET)

    private val xBrakeRequest = SwerveRequest.SwerveDriveBrake()

    fun stateActions() {
        Logger.recordOutput("swerve/state", currentState)
        if (OI.driveController.backButtonPressed) resetRotation(Rotation2d.kZero)
        when (currentState) {
            SwerveState.OrientToHub -> {
                val target =
                    if (robotInOwnAllianceZone) HUB_POSE
                    else state.Pose.nearest(listOf(FEED_RIGHT_POSE, FEED_LEFT_POSE))
                val snapAngle =
                    target.translation.minus(Shooter.getFieldRelativeShooterTranslation()).angle +
                        Rotation2d.k180deg +
                        operatorForwardDirection
                setControl(
                    orientHubRequest
                        .withTargetDirection(snapAngle)
                        .withVelocityX(0.0)
                        .withVelocityY(0.0)
                    //                        .withVelocityX(MaxSpeed * OI.velocityX())
                    //                        .withVelocityY(MaxSpeed * OI.velocityY())
                )

                // Shoot when ready
                val yawError =
                    abs(
                        state.Pose.rotation.rotateBy(operatorForwardDirection).degrees -
                            snapAngle.degrees
                    )
                Logger.recordOutput("swerve/orientToHubYawError", yawError)
                if (yawError < 2.0) {
                    Shooter.flywheelState = Shooter.FlywheelState.Firing
                    Indexer.currentState = Indexer.IndexerState.WaitingToShoot
                }
            }

            SwerveState.CardinalSnap -> {
                val autoSlowForScoring =
                    Shooter.flywheelState == Shooter.FlywheelState.Firing && robotInOwnAllianceZone
                val velocityX = if (autoSlowForScoring) OI.shootingVelocityX() else OI.velocityX()
                val velocityY = if (autoSlowForScoring) OI.shootingVelocityY() else OI.velocityY()
                setControl(
                    crossBumpRequest
                        .withTargetDirection(cardinalSnapDirection)
                        .withVelocityX(velocityX)
                        .withVelocityY(velocityY)
                )
            }

            SwerveState.FieldCentric -> {
                val autoSlowForScoring =
                    Shooter.flywheelState == Shooter.FlywheelState.Firing && robotInOwnAllianceZone
                val velocityX = if (autoSlowForScoring) OI.shootingVelocityX() else OI.velocityX()
                val velocityY = if (autoSlowForScoring) OI.shootingVelocityY() else OI.velocityY()
                val rotation = if (autoSlowForScoring) OI.shootingRotation() else OI.rotation()
                setControl(
                    fieldCentricRequest
                        .withVelocityX(velocityX)
                        .withVelocityY(velocityY)
                        .withRotationalRate(rotation)
                )
            }

            SwerveState.CrossBump -> {
                //                val targetY = if (state.Pose.y > MIDPOINT.y) HIGH_BUMP_Y else
                // LOW_BUMP_Y
                //                var ySpeed = crossBumpPIDController.calculate(state.Pose.y -
                // targetY.meters)
                //                ySpeed *= 1 - abs(OI.velocityX())
                //                if (DriverStation.getAlliance().get() == Red) ySpeed *= -1

                // crossBumpSnapAngle is set once when currentState is set to SwerveState.CrossBump
                setControl(
                    crossBumpRequest
                        .withTargetDirection(crossBumpSnapAngle)
                        .withVelocityX(OI.velocityX())
                        .withVelocityY(OI.velocityY())
                    //                        .withVelocityY(ySpeed)
                )
            }

            SwerveState.XBrake -> setControl(xBrakeRequest)
            SwerveState.AlignToTower -> {
                if (!climbPreAligned)
                    climbPreAligned =
                        driveToPose(
                            target =
                                state.Pose.nearest(
                                    listOf(LEFT_PRE_CLIMB_POSE, RIGHT_PRE_CLIMB_POSE)
                                ),
                            threshold = 3.inches,
                            maxSpeed = 1.5,
                            minSpeed = 0.6,
                        )
                else
                    driveToPose(
                        target = state.Pose.nearest(listOf(LEFT_CLIMB_POSE, RIGHT_CLIMB_POSE)),
                        threshold = 2.inches,
                        maxSpeed = 0.6, // m/s
                    )
            }
        }
    }

    fun stateTransitions() {
        when (currentState) {
            SwerveState.OrientToHub -> {
                if (!OI.orientToHub()) currentState = SwerveState.FieldCentric
            }

            SwerveState.CardinalSnap -> {
                if (abs(OI.rawRotation()) > 0.05) currentState = SwerveState.FieldCentric
                else if (OI.crossBump()) currentState = SwerveState.CrossBump
                else if (OI.xBrake()) currentState = SwerveState.XBrake
                else if (OI.alignToTower()) currentState = SwerveState.AlignToTower
                else if (OI.snapNorth() || OI.snapEast() || OI.snapSouth() || OI.snapWest())
                    currentState =
                        SwerveState.CardinalSnap // re-triggers setter to update snapTargetDirection
            }
            SwerveState.FieldCentric -> {
                if (OI.crossBump()) currentState = SwerveState.CrossBump
                else if (OI.xBrake()) currentState = SwerveState.XBrake
                else if (OI.alignToTower()) currentState = SwerveState.AlignToTower
                else if (OI.snapNorth() || OI.snapEast() || OI.snapSouth() || OI.snapWest())
                    currentState = SwerveState.CardinalSnap
                else if (OI.orientToHub()) currentState = SwerveState.OrientToHub
            }

            SwerveState.CrossBump -> {
                if (!OI.crossBump()) currentState = SwerveState.FieldCentric
            }

            SwerveState.XBrake -> {
                if (!OI.xBrake()) currentState = SwerveState.FieldCentric
            }

            SwerveState.AlignToTower -> {
                if (!OI.alignToTower()) currentState = SwerveState.FieldCentric
            }
        }
    }

    /**
     * Returns true if robot is in its own alliance zone, false if not. Accounts for which alliance
     * we are currently on.
     */
    var robotInOwnAllianceZone = true

    private fun isRobotInOwnAllianceZone(): Boolean {
        val currentX = SwerveDrivetrain.state.Pose.x
        return when (DriverStation.getAlliance().orElse(Red)) {
            Red -> currentX > RED_AUTO_LINE_X
            else -> currentX < BLUE_AUTO_LINE_X
        }
    }

    var robotInOpponentAllianceZone = false

    private fun isRobotInOpponentAllianceZone(): Boolean {
        val currentX = SwerveDrivetrain.state.Pose.x
        return when (DriverStation.getAlliance().orElse(Red)) {
            Red -> currentX < BLUE_AUTO_LINE_X
            else -> currentX > RED_AUTO_LINE_X
        }
    }

    private val posePIDController = PIDController(5.0, 0.0, 0.5)

    private val xLimiter = SlewRateLimiter(15.24)
    private val yLimiter = SlewRateLimiter(15.24)

    private val FieldCentricFacingAngleAlignments: SwerveRequest.FieldCentricFacingAngle =
        SwerveRequest.FieldCentricFacingAngle()
            .withHeadingPID(6.0, 0.0, 0.1)
            .withRotationalDeadband(0.05)
            .withForwardPerspective(SwerveRequest.ForwardPerspectiveValue.BlueAlliance)
            .withDriveRequestType(SwerveModule.DriveRequestType.Velocity)
            .withSteerRequestType(SwerveModule.SteerRequestType.MotionMagicExpo)

    /**
     * Drives to a pose using a PID controller
     *
     * @param target the desired Pose2d to drive to
     * @param threshold distance from target to consider "at target", in meters
     * @param maxRotation the maximum rate of rotation in rad/s
     * @param alwaysMaxSpeed whether the robot should go at max speed for the entire motion
     * @param minSpeed the slowest the robot will move in m/s if fullSpeed is false
     * @param intakeFirst if true, ignores target rotation and instead orients the robot so the
     *   intake (front, 0 degrees) faces toward the target
     * @return true if distance to target is < threshold
     */
    fun driveToPose(
        target: Pose2d,
        threshold: Distance = 0.inches,
        maxSpeed: Double = kSpeedAt12Volts.metersPerSecond,
        maxRotation: Double = MaxAutoRotationSpeed,
        alwaysMaxSpeed: Boolean = false,
        minSpeed: Double = 0.0,
        intakeFirst: Boolean = false,
    ): Boolean {
        Logger.recordOutput("DriveToPose target", target)
        val diff = state.Pose.translation - target.translation
        Logger.recordOutput("DriveToPose angle", diff.angle)
        val targetRotation = if (intakeFirst) (-diff).angle else target.rotation
        FieldCentricFacingAngleAlignments.withTargetDirection(targetRotation)

        Logger.recordOutput("DriveToPose norm", diff.norm)
        val output = posePIDController.calculate(diff.norm)
        Logger.recordOutput("DriveToPose output", output)
        val clampedOutput =
            if (alwaysMaxSpeed) sign(output) * maxSpeed
            else sign(output) * MathUtil.clamp(abs(output), minSpeed, maxSpeed)

        val angle = diff.angle
        val xSpeed = clampedOutput * angle.cos
        val ySpeed = clampedOutput * angle.sin

        val limitedX = xLimiter.calculate(xSpeed)
        val limitedY = yLimiter.calculate(ySpeed)

        setControl(
            FieldCentricFacingAngleAlignments.withVelocityX(limitedX)
                .withVelocityY(limitedY)
                .withMaxAbsRotationalRate(maxRotation)
        )

        return diff.norm < threshold.meters
    }

    private lateinit var simNotifier: Notifier
    private var lastSimTime = 0.0

    /* Keep track if we've ever applied the operator perspective before or not */
    private var hasAppliedOperatorPerspective = false

    init {
        if (Utils.isSimulation()) {
            startSimThread()
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    fun periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance()
                .ifPresent(
                    Consumer { allianceColor: DriverStation.Alliance? ->
                        setOperatorPerspectiveForward(
                            if (allianceColor == Red) kRedAlliancePerspectiveRotation
                            else kBlueAlliancePerspectiveRotation
                        )
                        hasAppliedOperatorPerspective = true
                    }
                )
        }

        robotInOwnAllianceZone = isRobotInOwnAllianceZone()
        robotInOpponentAllianceZone = isRobotInOpponentAllianceZone()
        Logger.recordOutput("swerve/isRobotInOwnAllianceZone", robotInOwnAllianceZone)
    }

    private fun startSimThread() {
        lastSimTime = Utils.getCurrentTimeSeconds()

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        simNotifier =
            Notifier(
                Runnable {
                    val currentTime = Utils.getCurrentTimeSeconds()
                    val deltaTime = currentTime - lastSimTime
                    lastSimTime = currentTime

                    /* use the measured time delta, get battery voltage from WPILib */
                    updateSimState(deltaTime, RobotController.getBatteryVoltage())
                }
            )
        simNotifier.startPeriodic(kSimLoopPeriod)
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    override fun addVisionMeasurement(visionRobotPoseMeters: Pose2d, timestampSeconds: Double) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds))
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * Note that the vision measurement standard deviations passed into this method will continue to
     * apply to future measurements until a subsequent call to [.setVisionMeasurementStdDevs] or
     * this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the
     *   form [x, y, theta]ᵀ, with units in meters and radians.
     */
    override fun addVisionMeasurement(
        visionRobotPoseMeters: Pose2d,
        timestampSeconds: Double,
        visionMeasurementStdDevs: Matrix<N3, N1>,
    ) {
        super.addVisionMeasurement(
            visionRobotPoseMeters,
            Utils.fpgaToCurrentTime(timestampSeconds),
            visionMeasurementStdDevs,
        )
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    override fun samplePoseAt(timestampSeconds: Double): Optional<Pose2d> {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds))
    }

    private val limelights = listOf("limelight-left", "limelight-back", "limelight-right")
    private val mt1Stddevs = VecBuilder.fill(.5, .5, 0.1)
    private val mt1MultiTagStddevs = VecBuilder.fill(.1, .1, 0.1)
    private var seeTag: Boolean = false

    /** Updates using MT1 */
    fun updateLimelights() {
        seeTag = false
        for (limelight in limelights) {
            LimelightHelpers.SetRobotOrientation(
                limelight,
                state.Pose.rotation.degrees,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            )
            val mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue(limelight)
            Logger.recordOutput("$limelight/mt1_pose", mt1.pose)
            val mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(limelight)
            Logger.recordOutput("$limelight/mt2_pose", mt2.pose)
            if (mt1.tagCount == 0) continue
            if (mt1.tagCount > 1) {
                seeTag = true
                addVisionMeasurement(mt1.pose, mt1.timestampSeconds, mt1MultiTagStddevs)
            } else addVisionMeasurement(mt1.pose, mt1.timestampSeconds, mt1Stddevs)
        }
        if (DriverStation.isDisabled()) {
            if (seeTag) {
                LED.currentState = LED.LedState.DisabledSeeTag
            } else {
                LED.currentState = LED.LedState.DisabledNoTag
            }
        }
    }

    private const val kSimLoopPeriod = 0.004 // 4 ms

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private val kBlueAlliancePerspectiveRotation: Rotation2d = Rotation2d.kZero

    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private val kRedAlliancePerspectiveRotation: Rotation2d? = Rotation2d.k180deg

    val MaxSpeed = kSpeedAt12Volts
    val MaxAngularRate = RotationsPerSecond.of(0.75)
    private val MaxAutoRotationSpeed =
        kSpeedAt12Volts.metersPerSecond /
            hypot(TunerConstants.BackLeft.LocationX, TunerConstants.BackLeft.LocationY)
}
